### ISSUE TITLE
create role / users table first

### ISSUE THREAD

**Issue by wkzhu** [level09/enferno#11]
Note: using sql implementation.
When trying to run `manage.py install` python complains that the tables don't exist.
I think it's worth mentioning somewhere that you need to create the role / users tables. I used your shell (which is very handy) to do so:

```
> python manage.py shell
>>> from extensions import db
>>> db.init_app(app)
>>> db.create_all()
```

Thanks for making this project - super cool.

**Comment by level09** [comment]
Hi @wkzhu, 

Thanks for checking out the project and the kind words. 
I Kind-of assumed the user will run the application which will in turn create all tables, that can be found here: 

https://github.com/level09/enferno/blob/sql/app.py#L29

Thanks for the note though, I'll try to update the readme and push some new updates soon.

**Comment by wkzhu** [comment]
actually I somehow cloned a version without this line of code. my bad!
