### ISSUE TITLE
./manage.py install error

### ISSUE THREAD

**Issue by redtreelchao** [level09/enferno#12]
cry for help.

>   File "/usr/local/lib/python2.7/site-packages/bcrypt/**init**.py", line 82, in hashpw
>     hashed = _bcrypt.ffi.new("unsigned char[]", 128)
> AttributeError: 'module' object has no attribute 'ffi

mongodb 3.2
python 2.7

**Comment by level09** [comment]
Hi @redtreelchao, 

May I ask which OS are you using ?
