### ISSUE TITLE
Interesting Issue when setting up a flask testing harness

### ISSUE THREAD

**Issue by rmoskal** [level09/enferno#2]
I downloaded enferno to compare it to the way I set up my own flask apps, it's pretty similar, and pretty similar to what most people do I think.  I made some tweaks which I may share with you later, however there's a problem when setting of a flask testing harness using the recommended method:

```
class TwinesTestCase(unittest.TestCase):

    def setUp(self):
        os.environ["FLASK_ENV"] = "test"
       cfg = Konfigure().config
       app = create_app(cfg)
       self.app = app.test_client()

   def tearDown(self):
      db = connect('test')
      db.drop_database('test')
```

One test case works fine, but on the second one I get the following:

> AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at    
> 0x7f751107bf50> and <flask.blueprints.Blueprint object at 0x7f751107b610>.  Both share the same 
> name "user".  Blueprints that are created on the fly need unique names."

It's because you have admin as a module level variable in extensions.py.  So on the second test instantiation you get an error at line 35 in your app.py.  

Your app factory doesn't let itself be instantiated multiple times (the point of the pattern).  Creating admin in the register_extensions method fixes the immediate problem, though I'm not sure how some of the other extensions are affected by this same sort of thing.

You may want to revisit this.

**Comment by level09** [comment]
Thank you Roboert for pointing this out. 

I will have a look at this tomorrow, Also feel free to send any suggestions/pull requests.
