### ISSUE TITLE
Fails when redis is on remote system

### ISSUE THREAD

**Issue by joej** [level09/enferno#22]
If you run redis on a remote machine, enferno simply won't work.

No amount of configuration (.env, rm .env, CELERY_XXX=yyy flask run, settings.py, etc) will prevent celery from trying to connect to redis://localhost:6379 -- either ::1 or 127.0.0.1

Could it be this?
https://stackoverflow.com/questions/47706343/celery-ignoring-config-values
https://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern

**Comment by joej** [comment]
CELERY_BROKER_BACKEND <-- ??
vs. CELERY_RESULT_BACKEND

**Comment by joej** [comment]
Grrrrr -- SESSION_TYPE. Comment that line out, and you won't get attempts to use redis://localhost

**Comment by level09** [comment]
Hi @joej 

If Flask-session is causing this problem (it indeed connects to localhost by default) 
You have multiple options: 

- supply your own **SESSION_REDIS** config, it has to be a redis.Redis instance, more info here: 

https://github.com/fengsp/flask-session/blob/a88f07e7260ae582b0744de42e77c4625e6884ea/docs/index.rst

- switch the session to another type , e.g file system

- disable the server side sessions extension altogether 

Let me know if that helps.

**Comment by joej** [comment]
I think the SESSION_TYPE (null/commented) made it go away. I can try re-enabling then configuring SESSION_REDIS.
So, redis on /10, /11 and also sesions on /12. 

Now, the challenge is to get the flask security to STOP trying to send email automatically. That project has its own issues with hijacking or monkey patching the function to send email.   There is not configuration to enable/disable.

I know you're leveraging other projects to build a higher level framework, but enferno is inheriting their issues.

**Comment by joej** [comment]
Issue with Flask-sessions. Solved by additional config/removable of defaults in enferno.

**Comment by level09** [comment]
Hi @joej 

I have actually identified the sessions issue (the bug happens when running the framework via Docker) the fix is already deployed in the latest version.

Regarding Flask security , I have replaced it with https://pypi.org/project/Flask-Security-Too/ as some guys recommended, feel free to share any other notes you may have.
