### ISSUE TITLE
Getting 500 error while starting the app

### ISSUE THREAD

**Issue by sakkeerhussaina** [level09/enferno#28]
Getting the below message at start. Not sure what I missed.

500
Sorry, something went wrong on our system. Don't panic, we are fixing it! Please try again later.

![image](https://user-images.githubusercontent.com/58373883/186980605-06ec2905-41d5-48c4-bf91-4712b5b495eb.png)

**Comment by ladeane00** [comment]
I am also having this issue

**Comment by level09** [comment]
Hi, 

a couple of things to check. 

- do you have a .env file in your root directory ? you can copy and modify the .env-sample , or just use the following file that uses sqlite database: 
```
#Enferno
SECRET_KEY=3nF3Rn@
FLASK_APP=run.py
FLASK_DEBUG=1
MAIL_USERNAME=sendgrid
MAIL_PASSWORD=sendgrid_secure_password
SQLALCHEMY_DATABASE_URI=sqlite:///db
#Docker
COMPOSE_PROJECT_NAME=enferno
PYTHONUNBUFFERED=true
```

- can you turn on FLASK_DEBUG and share the detailed error message ?  that could give us a better insight about what's going on.

**Comment by level09** [comment]
Didn't hear back from you, feel free to re-open if you still get this error :)
