### ISSUE TITLE
error when enabling email  authentication

### ISSUE THREAD

**Issue by vlasvlasvlas** [level09/enferno#29]
Hi! i was testing this framework, really looks amazing!

I have an issue, i was trying to enable email auth (validation by email) and got an error.

this is what i changed:

on settings.py:
-     **SECURITY_CONFIRMABLE = True** (from False to True)

Then i try to register (flask run on dev mode) and got this message:

`jinja2.exceptions.UndefinedError: 'flask_security.forms.ConfirmRegisterForm object' has no attribute 'name'`

I want to authenticate via email (send email token, click on it, and validate user mail )

do i need to make any more changes?

thanks

**Comment by level09** [comment]
Hi There :) and thanks for passing by. 

I was able to reproduce the error and rolled a quick fix. 

Let me know if you encounter any further issues.

**Comment by vlasvlasvlas** [comment]
Hi! Nice! thanks a lot for the quick answer, the framework is great! :)

**Comment by level09** [comment]
Thank you ! you're welcome , glad to help 😊
