### ISSUE TITLE
Question on REST API generation

### ISSUE THREAD

**Issue by scheung38** [level09/enferno#8]
Does your framework also generates Rest API, such that if the front end (could be AngularJS or whatever) is calling for a list of 

```
class Title(db.Document):
    title_list = ['Mr', 'Mrs', 'Ms', 'Prof', 'Dr', 'Eng']
    title = db.StringField(max_length=5, required=True)

    def __unicode__(self):
        return '%s' % self.title


class MaritalStatus(db.Document):
    marital_list = ['Married', 'Single', 'Divorced',
                'Widowed', 'Living Together', 'Separated', 'Other']
    marital = db.StringField(max_length=25, required=True)

    def __unicode__(self):
        return '%s' % self.marital
```

then returns a JSON response, if not then I would maybe use?:

https://github.com/closeio/flask-mongorest

Just need an API that reads from a database and present to user registration scenario in the form of dropdowns to choice from. Just don't want to duplicate if framework already has it. Thanks

**Comment by level09** [comment]
Hi @scheung38 , 
There is no automatic rest APIs but it would be very easy to create some endpoints for that and return MaritalStatus.objects.to_json() for example. 

on the other hand, mongodb has some http rest interfaces which you can check here: http://docs.mongodb.org/ecosystem/tools/http-interfaces/

**Comment by scheung38** [comment]
In the flask-mongoengine examples/biggerapp, tried to make simple API, but each time just returning keys and no values?


in app.py added:
```
from views import index, test
app.add_url_rule('/', view_func=index)
app.add_url_rule('/api/test', view_func=test)  <- added
```
and in views.py added
```
from bson.json_util import dumps

def index():
    # As a list to test debug toolbar
    Todo.objects().delete()  # Removes
    Todo(title="Simple todo A", text="12345678910").save()  # Insert
    Todo(title="Simple todo B", text="12345678910").save()  # Insert
    Todo(title="New on Sunday", text="100", done=True).save()  # Test
    Todo.objects(title__contains="B").update(set__text="Hello world")  # Update
    Todo.objects(title__contains="Sunday").update(set__title="Zahara is back")
    todos = list(Todo.objects[:10])
    todos = Todo.objects.all()
    return flask.render_template('index.html', todos=todos)

def test():
    return dumps(Todo.objects.all()) <- added
```

The main index page is fine as before with new data, but the 
http://0.0.0.0:4000/api/test end point returns empty keys:
```
[["id", "title", "text", "done", "pub_date"], ["id", "title", "text", "done", "pub_date"], ["id", "title", "text", "done", "pub_date"]]
```
Also tried:

```
return dumps(Todo.objects(title__='Simple todo A'))
```
But still returning get the keys and no values? Suspect I am not calling the right object? But it is a globally imported object as far as the views.py module is concerned?

Even if modifying original index function:
```
# return flask.render_template('index.html', todos=todos)
    return dumps(Todo.objects.all())
```
It is still keys returned?

But you suggested .objects.to_json(), doesnt return json but string?

"[{\"text\": \"12345678910\", \"_id\": {\"$oid\": \"5609516129c46e2e16cc24e4\"}, \"pub_date\": {\"$date\": 1443454833061}, \"done\": false, \"title\": \"Simple todo A\"}, {\"text\": \"Hello world\", \"_id\": {\"$oid\": \"5609516129c46e2e16cc24e5\"}, \"pub_date\": {\"$date\": 1443454833173}, \"done\": false, \"title\": \"Simple todo B\"}, {\"text\": \"100\", \"_id\": {\"$oid\": \"5609516129c46e2e16cc24e6\"}, \"pub_date\": {\"$date\": 1443454833179}, \"done\": true, \"title\": \"Zahara is back\"}]"

**Comment by level09** [comment]
Yes, that is what you need, JSON IS a string. if you would like to improve this further, add the mime type 

```
form flask import Response
return Response(Todo.objects.to_json(),mimetype='application/json')
```

**Comment by scheung38** [comment]
thanks, also anyway to get pprint to make pretty prints ?

**Comment by level09** [comment]
I don't usually care about the output format, if you install this: 
https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc
it will format it for you.
