### ISSUE TITLE
Want to use bootstrap templates - is there a way ?

### ISSUE THREAD

**Issue by maxMidius** [level09/enferno#9]

**Comment by maxMidius** [comment]
I added  the following to  app.py
from flask_bootstrap import Bootstrap

Bootstrap(app)  in create_app
Seems to work - but not sure if this is the best way .. Thanks

**Comment by level09** [comment]
it is fairly simple to integrate Bootstrap (or any css framework), you can manually copy the css/javascript files to the static directory. and update the layout.html/index.html 

Here is one guide to integrate skeleton css: 
https://medium.com/project-enferno/tip-integrate-the-new-skeleton-css-framework-with-enferno-in-2-min-541e9e5cf87f

Hope that helps
